language: python

python:
    - '3.6.9'
    - '3.7.3'
    - '3.7.4'
    - '3.7.5'
    - '3.7.6'
    - '3.7.7'
    - '3.8.0'

os:
    - linux
    

cache: pip

before_install:
    -  sudo apt-get update && apt-get install --assume-yes --no-install-recommends python3-pip>=20.0.2

sudo: true

install:
    - python setup.py install

script:
    - pytest
