language: python

python:
    - '3.6'
    - '3.7'

os:
    - linux

cache: pip

before_install:
    - pip3 install -U pip
    - pip3 install "scipy<=1.5.4"
    - pip3 install "pandas<=1.1.5"

install:
    - python3 setup.py install

script:
    - pytest
